server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs with user extraction from URLs
  - job_name: invoice-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: invoice-app
          service: invoice-api
          __path__: /var/log/backend/logs/application.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            url: url
            requestId: requestId
      - regex:
          expression: '.*organizationId=(?P<organizationId>[^&\s]+)'
          source: url
      - regex:
          expression: '.*/(?P<userEmail>[^/]+@[^/]+)/.*'
          source: url
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          organizationId:
          userEmail:
          requestId:
      - output:
          source: message

  # Combined logs with user extraction from URLs
  - job_name: invoice-combined-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: invoice-combined
          service: invoice-api
          __path__: /var/log/backend/logs/combined.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            url: url
            requestId: requestId
      - regex:
          expression: '.*organizationId=(?P<organizationId>[^&\s]+)'
          source: url
      - regex:
          expression: '.*/(?P<userEmail>[^/]+@[^/]+)/.*'
          source: url
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          organizationId:
          userEmail:
          requestId:
      - output:
          source: message

  # Access logs with user data extraction
  - job_name: invoice-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: invoice-access
          service: invoice-api
          __path__: /var/log/backend/logs/access*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            method: method
            url: url
            statusCode: statusCode
            userId: userId
            organizationId: organizationId
            requestId: requestId
            ip: ip
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          method:
          statusCode:
          userId:
          organizationId:
          requestId:
          ip:
      - output:
          source: message

  # Exception logs
  - job_name: invoice-exception-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: invoice-exceptions
          service: invoice-api
          __path__: /var/log/backend/logs/exceptions.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            error_type: error_type
            error_code: error_code
            stack_trace: stack_trace
            userId: userId
            organizationId: organizationId
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          error_type:
          error_code:
          userId:
          organizationId:
      - output:
          source: message

  # Error logs
  - job_name: invoice-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: invoice-errors
          service: invoice-api
          __path__: /var/log/backend/logs/error.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            error: error
            userId: userId
            organizationId: organizationId
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          userId:
          organizationId:
      - output:
          source: message