apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://invoice-prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://invoice-loki:3100
    uid: loki
    editable: true
    jsonData:
      maxLines: 1000